### ISSUE TITLE
Not Working on Newer Eclipse Version

### ISSUE THREAD

**Issue by diegopaniago** [IntelliJIdeaKeymap4Eclipse/IntelliJIdeaKeymap4Eclipse#10]
The plugin is not compatible with the newer version of Eclipse.
Version: 2019-09 R (4.13.0)
Build id: 20190917-1200

**Comment by IntelliJIdeaKeymap4Eclipse** [comment]
I tested it on Windows and it worked. Can you please try it again, maybe with a fresh Eclipse installation? Please give me more context in case it doesn't work.

**Comment by diegopaniago** [comment]
Ĩ am using eclipse on ubunto 18.04.3 LTS -> I need this version because the project don`t run on newer.
The plugin not appear on market, I need click to open browser to find.
I tried again but the problem was not solved.
![image](https://user-images.githubusercontent.com/12701214/69238276-f3eda500-0b6d-11ea-8745-b781513710ae.png)
![image](https://user-images.githubusercontent.com/12701214/69238718-0d432100-0b6f-11ea-9884-55b6ab091c49.png)
![image](https://user-images.githubusercontent.com/12701214/69239473-ad4d7a00-0b70-11ea-87bb-5240a2547a85.png)

**Comment by IntelliJIdeaKeymap4Eclipse** [comment]
Please try it again.

I updated the Eclipse Marketplace listing to support Linux. Afterwards I could successfully install it.

Please note that I have very limited spare time and therefore the shortcuts / keymap haven't been tested on Ubuntu yet.

Feel free to submit bugs or a pull request.

**Comment by diegopaniago** [comment]
Thank you so much for this fix. Works very whell now.
